export const SET_PAYMENT_CARDNUMBER_FORM = 'SET_PAYMENT_CARDNUMBER_FORM';
export const SET_PAYMENT_EXPIREDATE_FORM = 'SET_PAYMENT_EXPIREDATE_FORM';
export const SET_PAYMENT_SECUTIRYCODE_FORM = 'SET_PAYMENT_SECUTIRYCODE_FORM';
export const SET_PAYMENT_CARDHOLDERNAME_FORM =
  'SET_PAYMENT_CARDHOLDERNAME_FORM';
export const SET_PAYMENT_IDENTIFICATIONNUMBER_FORM =
  'SET_PAYMENT_IDENTIFICATIONNUMBER_FORM';
export const SET_PAYMENT_TOKEN_FORM = 'SET_PAYMENT_TOKEN_FORM';
export const SET_PAYMENT_CARDFLAG_FORM = 'SET_PAYMENT_CARDFLAG_FORM';
export const SET_CLEAR_FORM = 'SET_CLEAR_FORM';
