export const SET_GAME_FORM_TYPE = 'SET_GAME_FORM_TYPE';
export const SET_GAME_FORM = 'SET_GAME_FORM';
export const SET_GAME_NAME_FORM = 'SET_GAME_NAME_FORM';
export const SET_CLEAR_FORM = 'SET_CLEAR_FORM';
