export const SET_GAME_FORM_TYPE = 'SET_GAME_FORM_TYPE';
export const SET_GAME_FORM_NUMBERS = 'SET_GAME_FORM_NUMBERS';
export const SET_GAME_FORM_NAME = 'SET_GAME_FORM_NAME';
export const SET_CLEAR_FORM = 'SET_CLEAR_FORM';
